package com.capgemini.SalesOrder.zgwsample_srv;
/*
 Auto-Generated by SAP NetWeaver Gateway Productivity Accelerator, Version 1.1.1
 */

/**
 * A class that holds configurations for the service version. 
 */
public class ServiceVersionConfigurations 
{
	public static final String CATALOG_SERVICE_URL = "/sap/opu/odata/iwfnd/CatalogService/";
	public static final String TECHNICHAL_SERVICE_NAME = "";
	public static final int TECHNICHAL_SERVICE_VERSION_MIN = 0;
	public static final int TECHNICHAL_SERVICE_VERSION_MAX = 0;
}