package com.capgemini.SalesOrder.zgwsample_srv.v0.helpers;
/*

 Auto-Generated by SAP NetWeaver Gateway Productivity Accelerator, Version 1.1.1

*/
import java.util.ArrayList;
import java.util.List;

/**
 * A wrapper class for the listeners of request handler.
 */
public class ListenerWrapper
{
    // the listener
    private IZGWSAMPLE_SRVRequestHandlerListener listener;
    // the list of request IDs
    private List<ZGWSAMPLE_SRVRequestID> requestIDs;
    
    /**
     * Constructs a new listener wrapper with the given listener
     * and request IDs.
     * 
     * @param listener - the request handler listener.
     * @param requestIDs - may be passed as an array or as a sequence of request IDs.
     */
    public ListenerWrapper(IZGWSAMPLE_SRVRequestHandlerListener listener, ZGWSAMPLE_SRVRequestID... requestIDs)
    {
        this.listener = listener;
        
        this.requestIDs = new ArrayList<ZGWSAMPLE_SRVRequestID>();
        for (ZGWSAMPLE_SRVRequestID requestID : requestIDs)
        {
            this.requestIDs.add(requestID);
        }
    }

    /**
     * Returns the listener.
     * @return the listener.
     */
    public IZGWSAMPLE_SRVRequestHandlerListener getListener()
    {
        return listener;
    }

    /**
     * Returns the request IDs.
     * @return - the request IDs.
     */
    public List<ZGWSAMPLE_SRVRequestID> getRequestIDs()
    {
        return requestIDs;
    }
}